CREATE TABLE ufo_sighting
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location  VARCHAR(255),
    date_time TIMESTAMP WITHOUT TIME ZONE,
    color     VARCHAR(255),
    shape     VARCHAR(255),
    quantity  INTEGER,
    CONSTRAINT pk_ufosighting PRIMARY KEY (id)
);